version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - API_URLS=${API_URLS}
    volumes:
      - ./logs:/app/logs
